"""Rename password in User model for abstration

Revision ID: f8cef14b48f5
Revises: f374f1eef23e
Create Date: 2025-06-20 13:48:51.086963

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8cef14b48f5"
down_revision: Union[str, Sequence[str], None] = "f374f1eef23e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(), nullable=False))
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("users", "password")
    # ### end Alembic commands ###
